---
#title: "Lab Website"
---


<h4 style="text-align:left;">**Microbial Biodiversity: Evolution To Ecosystems**:</h4>
Microorganisms are the most abundant and diverse life forms on Earth. They have fast reproductive rates and evolve rapidly to changes in their environment. Microbes also carry out processes that are critical for the stability of engineered, environmental, and host-associated ecosystems.

From test tubes to the globe, we study the ecology and evolution of microbial communities. We are interested in the factors that generate and maintain microbial biodiversity. In turn, we seek to understand the implications of microbial diversity for ecosystem functioning. To address these questions, our team uses a combination of molecular biology, modeling, data mining and synthesis, laboratory experiments, and field surveys in a wide range of habitats. 

For additional information and news, visit the <a href="https://lennon.bio.indiana.edu/index.php?title=Main_Page">Lab Wiki</a> and follow us on <a href="https://twitter.com/jaytlennon">Twitter</a>. 
Data and code for some of our projects can be found on <a href="https://github.com/lennonlab">GitHub</a>. 

<h4 style="text-align:left;">**Contact**:</h4>

<p>
<a href="https://www.indiana.edu/~microbes/people.php/cfm#Lennon"> Jay T. Lennon</a>, <a href="https://biology.indiana.edu/index.html">  Department of Biology</a>, <a href="https://www.indiana.edu/">Indiana University</a>, 261 Biology Building, <a href="http://goo.gl/PIjsr5">1001 East 3rd Street</a>, <a href="http://bloomington.in.gov/">Bloomington, IN</a> 47405 USA, 812-856-0962 (office), 812-856-7235 (lab), <a href="mailto:lennonj@indiana.edu">lennonj@indiana.edu</a> 
</p>
